version: "3"

tasks:
  install-requirements:
    desc: install requirements
    cmds:
      - mkdir tmp
      - task: download-protoc
      - task: unzip-protc
      - mkdir -p bin
      - rm -rf bin/protoc
      - task: locate-protoc
      - rm -rf ./tmp
      - task: goget-grpc
  download-protoc:
    dir: tmp
    cmds:
      - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-aarch_64.zip --output protoc.zip
  unzip-protc:
    dir: tmp
    cmds:
      - unzip ./protoc.zip -d protoc
  locate-protoc:
    dir: tmp
    cmds:
      - mv -f ./protoc/ ../bin
  goget-grpc:
    cmds:
      - go get -u google.golang.org/grpc
      - go get -u github.com/golang/protobuf/protoc-gen-go
      - go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
  protoc:
    desc: gen protoc
    cmds:
      - mkdir -p internal
      - bin/protoc/bin/protoc --go_out=plugins=grpc:./ proto/*.proto
      - mkdir -p doc/proto
      - bin/protoc/bin/protoc --doc_out=html,index.html:./doc/proto proto/*.proto
  run:
    desc: run
    cmds:
      - go run cmd/server/server.go &
      - sleep 1
      - go run cmd/client/client.go
      - sleep 1
      - pkill server
