version: "3"

tasks:
  install-requirements:
    desc: install requirements
    cmds:
      - mkdir tmp
      - task: download-protoc
      - task: unzip-protc
      - mkdir -p bin
      - rm -rf bin/protoc
      - task: locate-protoc
      - rm -rf ./tmp
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
  download-protoc:
    dir: tmp
    cmds:
      - curl -L https://github.com/protocolbuffers/protobuf/releases/download/v21.4/protoc-21.4-linux-x86_64.zip --output protoc.zip
  unzip-protc:
    dir: tmp
    cmds:
      - unzip ./protoc.zip -d protoc
  locate-protoc:
    dir: tmp
    cmds:
      - mv -f ./protoc/ ../bin
  protoc:
    desc: gen protoc
    cmds:
      - mkdir -p internal
      - bin/protoc/bin/protoc --go_out=. --go-grpc_out=require_unimplemented_servers=false:. proto/*.proto
  run:
    desc: run
    cmds:
      - go run cmd/server/server.go &
      - sleep 1
      - go run cmd/client/client.go
      - sleep 1
      - pkill server
